### ISSUE TITLE
Resource Usage not dropping after scaling down replicas in a deployment

### ISSUE THREAD

**Issue by abhranilc** [cloudera/yunikorn-k8shim#29]
This issue occurred while following https://github.com/cloudera/yunikorn-core/blob/master/docs/user-guide.md
I am using docker-for-desktop Kubernetes on my Mac 
I am scheduling an nginx service via yunikorn as mentioned in the guide. I am editing the nginx deployment to scale up the number of replicas to a high number which cannot be spawned due to unavailability of resources (some pods are pending). Now, when I edit the deployment again to scale down the number of replicas, the resource usage and number of running applications do not update on the yunikorn UI though k8s dashboard shows that the pods have been deleted.  Also on the UI, under the cluster info tab, the application and container counts do not seem to be getting updated in this scenario.

**Comment by abhranilc** [comment]
Steps to reproduce: 
I started from a fresh setup of yunikorn on docker-for desktop

**Comment by abhranilc** [comment]
<img width="1423" alt="pic0" src="https://user-images.githubusercontent.com/3633725/63507550-9a85c380-c4f5-11e9-9ef0-b12cc929fa9b.png">
<img width="1424" alt="pic1" src="https://user-images.githubusercontent.com/3633725/63507557-9f4a7780-c4f5-11e9-87aa-07e4585e9d6e.png">
<img width="1432" alt="pic2" src="https://user-images.githubusercontent.com/3633725/63507564-a4a7c200-c4f5-11e9-8cae-1d905015a7a2.png">

**Comment by abhranilc** [comment]
Did a nginx deployment as in the examples
<img width="356" alt="pic5" src="https://user-images.githubusercontent.com/3633725/63507726-036d3b80-c4f6-11e9-9488-fcf39efb30f1.png">
<img width="1425" alt="pic6" src="https://user-images.githubusercontent.com/3633725/63507729-07995900-c4f6-11e9-85a3-2d770dc05908.png">
<img width="1430" alt="pic7" src="https://user-images.githubusercontent.com/3633725/63507738-0c5e0d00-c4f6-11e9-8b90-232b12c80b89.png">

**Comment by abhranilc** [comment]
Edited the deployment to scale up the replicas to 5. Only 3 were scheduled, 2 were pending
<img width="668" alt="pic16" src="https://user-images.githubusercontent.com/3633725/63507834-43ccb980-c4f6-11e9-98b2-4cdd22ccbe23.png">
<img width="1427" alt="pic17" src="https://user-images.githubusercontent.com/3633725/63507843-4a5b3100-c4f6-11e9-991d-db3618820c71.png">
<img width="1431" alt="pic18" src="https://user-images.githubusercontent.com/3633725/63507849-4fb87b80-c4f6-11e9-8e5d-160495e79f91.png">
<img width="1430" alt="pic19" src="https://user-images.githubusercontent.com/3633725/63507860-547d2f80-c4f6-11e9-9eca-727cf7db584a.png">

**Comment by abhranilc** [comment]
Again edited the deployment to scale down the number of replicas to 1. But yunikorn UI is not showing the change. Moreover, editing the deployment to make the number of replicas 2 from here also does not work. yunikorn still seems to think that resource is being used by 3 pods while it is not the case.

<img width="636" alt="pic20" src="https://user-images.githubusercontent.com/3633725/63508101-e1c08400-c4f6-11e9-902b-69a32102a484.png">
<img width="1431" alt="pic21" src="https://user-images.githubusercontent.com/3633725/63508117-e84efb80-c4f6-11e9-8eee-4ee6ad361146.png">
<img width="1426" alt="pic22" src="https://user-images.githubusercontent.com/3633725/63508127-ee44dc80-c4f6-11e9-8b90-935999c4f2ac.png">
<img width="1429" alt="pic23" src="https://user-images.githubusercontent.com/3633725/63508137-f3a22700-c4f6-11e9-976c-abc0181c8a24.png">
<img width="1432" alt="pic24" src="https://user-images.githubusercontent.com/3633725/63508148-f866db00-c4f6-11e9-8060-e512cb34eee5.png">

**Comment by abhranilc** [comment]
had closed the issue by mistake. please consider this open

**Comment by abhranilc** [comment]
Top of git log on my local
<img width="653" alt="Screen Shot 2019-08-22 at 12 37 19 PM" src="https://user-images.githubusercontent.com/3633725/63508465-a70b1b80-c4f7-11e9-9306-74824b67f6a4.png">

**Comment by yangwwei** [comment]
Thanks @abhranilc, I should have some tomorrow to replay what you did here and see what happens. I have tried to update replicas in a deployment, but I just hope all the newly created pods are having desired info as we expected, such as applicationId, queue name.

**Comment by yangwwei** [comment]
hi @abhranilc 

I just tried the scenario of scaling a deployment from 1 to 3 to 5. On my laptop, scale-up to 3 is fine and all pods are scheduled; scale-up to 5 left 2 pods pending, but that is expected because I can see warnings from K8s UI that saying the resource is not enough to launch all 5 pods. That's why I get 3 running, 2 pending. So this seems to work fine.

Then I tried the scale-down, it also works. After my deployment scales from 3 to 1, I was able to see containers get released from log, and then I go to the UI. The application page shows only 1 allocation left, and queues page also have updated the capacity being used.

Am I missing anything here?
Thanks

**Comment by yangwwei** [comment]
Got the issue reproduced after some offline discussion with @abhranilc . Looks like this issue can be triggered after a deployment scales beyond node's capacity, when we scale down after that, seems like containers somehow were not properly released. Looking into this now.
