### ISSUE TITLE
Pods stuck in Pending state

### ISSUE THREAD

**Issue by abhranilc** [cloudera/yunikorn-k8shim#41]
Hi, there seems to be some problem with the commit, https://github.com/cloudera/yunikorn-k8shim/commit/1d07b5572f4a3bd03a9684975cf7b150c38c5be2. All pods are stuck in pending state, tested for nginx as well as spark-pi. All subsequent commits seem to suffer with the same symptoms. Upto the previous commit, https://github.com/cloudera/yunikorn-k8shim/commit/fab56e0869f4d727848878c4ae2f55daeddea300, pods are running fine. I ran in to this while testing the closure of the issue https://github.com/cloudera/yunikorn-k8shim/issues/29

Steps to reproduce:
Build 2 separate images of yunikorn-scheduler-k8s from the above 2 commits and try to schedule nginx. 

Note: I was using docker-for-desktop

**Comment by yangwwei** [comment]
Hi @abhranilc 

The commit adds acls for queues, I suspect if this line https://github.com/cloudera/yunikorn-k8shim/blob/cafcfae3d04725e83775f784c7bed09439959065/conf/queues.yaml#L5 is missed in your `queues.yaml` file. If that's not the case, I'll take a look tomorrow.

**Comment by sunilgovind** [comment]
Yes. It seems like the same issue. @yangwwei  i think lets set submitacl to * if user doesnt specify in the spec file ?

**Comment by yangwwei** [comment]
> Yes. It seems like the same issue. @yangwwei i think lets set submitacl to * if user doesnt specify in the spec file ?

Yeah, that makes sense to me @sunilgovind . I am OK to have non-restriction (no-security) with the default setup. @wilfred-s what do you think?

**Comment by abhranilc** [comment]
Yes I confirm that is the case. Closing the issue

**Comment by wilfred-s** [comment]
All examples have been updated to include the `submitacl = "*"` on the root queue.
We need to have that on all examples. However we cannot allow the code to add it if it is missing as it could override all security that is set. Security must always be a "fail closed" or "default deny" setup. If we do not do that in the code we would immediately start introducing security holes.
