### ISSUE TITLE
K8s client QPS/Burst should be configurable in the shim

### ISSUE THREAD

**Issue by yangwwei** [cloudera/yunikorn-k8shim#44]
When we do perf testing, we found the interaction between shim and K8s sometimes goes pretty slow. It turns out the client is throttling parallel requests. 
![image (4)](https://user-images.githubusercontent.com/14214570/65217900-e2453e00-dae7-11e9-8d6c-6c37be87b2f5.png)

This was controlled by client-side configuration `QPS` and `Burst`. We need to expose them to be configurable. So we can tune these parameters when necessary.

**Comment by TaoYang526** [comment]
@yangwwei  Attached PR for this issue,  please help to review. Thanks.

**Comment by yangwwei** [comment]
Resolved by #55
