### ISSUE TITLE
Helm chart not setup rbac role for scheduler.

### ISSUE THREAD

**Issue by baikai** [cloudera/yunikorn-k8shim#45]
Helm chart not setup rbac role for scheduler, yunikorn-scheduler pods started by default:default service account, but default sa may has no privilege to list some api resources(e.g. node, pod, configmap...), it will cause yunikorn-scheduler-k8s container start fail.

User can run ‘kubectl create -f ./yunikorn-rbac.yaml’ manually before run helm charts, but is not convenient。

My suggestions for improving k8shim charts are as follows:
1 Add yunikorn-rbac.yaml
2 Create new sa for scheduler instead of use default sa
3 Create new namespaces to place the scheduler pods

**Comment by yangwwei** [comment]
You are right @baikai 
I found some other changes in another workspace of mine, forgot to merge those in.
Thanks for identifying the issue, I'll add a patch shortly.

**Comment by yangwwei** [comment]
Hi @baikai 
Please see if https://github.com/cloudera/yunikorn-k8shim/commit/8ddea3bb719f1bf6a22a9cecf413f510cc0134d7 resolves this issue.

**Comment by baikai** [comment]
Thanks for your quick fix, try it in my env and it works.
