### ISSUE TITLE
Length of dispatcher's event channel should be configurable

### ISSUE THREAD

**Issue by yangwwei** [cloudera/yunikorn-k8shim#46]
This should be exposed as a CLI option which can be configured during startup.

**Comment by TaoYang526** [comment]
Hi, @yangwwei FYI, I think it's better to change default value of the event channel from 1024 to 1024*1024.

**Comment by yangwwei** [comment]
Agreed. We had some discussion today and we agree to increase the default to a bigger one. 1024*1024 looks good. Maybe we can just increase it to this number now, leave the configuration change later. Would you like to create a PR for this?

**Comment by TaoYang526** [comment]
Thanks, If you don't mind, I would like to create a PR to handle all requirements in this issue. I plan to add a CLI option named "eventChannelCapacity", then initialize the event channel of dispatcher when calling dispatcher.Start(configs), thoughts?

**Comment by yangwwei** [comment]
Sure, that will be even better!

**Comment by TaoYang526** [comment]
Thanks @yangwwei. I have attached PR #50 for this.

**Comment by yangwwei** [comment]
this is resolved by #50
