### ISSUE TITLE
Failed to use persistent volume

### ISSUE THREAD

**Issue by TaoYang526** [cloudera/yunikorn-k8shim#66]
I have tested launching pod with PVC based on YK and found that although the pod can be bound successfully but unable to mount volumes.
Error message:
```
  Warning     FailedMount     1s    kubelet, node-xxx  Unable to mount volumes for pod "pod-xxx": timeout expired waiting for volumes to attach or mount for pod...
```
I can see that CheckVolumeBinding predicate checks volumes via calling volumeBinder#FindPodVolumes, but can't find where to bind pod volumes as default scheduler of K8s did in Scheduler#bindVolumes before binding pod with a node. 
I'm not sure if this is in the schedule or just something missed, @wilfred-s  @yangwwei could you please take a look at this issue? Thanks.

**Comment by wilfred-s** [comment]
How did you create the PVC what kind of volume are you referencing and what are the setting for the PVC and volume?
I have tested PVC and volume mounting and it worked for me but I have seen failures when the volume is not in the zone or when auto creating a volume took a long time.

**Comment by yangwwei** [comment]
I also have some doubts about missing calling bind volumes, this is actually one problem I've been looking at when we do the integration with our internal products. I have a patch for this, @TaoYang526  could you please help to check if the changes in PR #68 works for you?

**Comment by TaoYang526** [comment]
Thanks @wilfred-s  @yangwwei for your attentions.
> How did you create the PVC what kind of volume are you referencing and what are the setting for the PVC and volume?

Some details of my test are as follows:
(1) Before starting this test, we have serveral local PVs configured like this:
```
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                         STORAGECLASS   REASON   AGE
local-pv-1506073c   3519Gi     RWO            Delete           Available                                 fast-disks              92d
local-pv-3f58e927   3519Gi     RWO            Delete           Available                                 fast-disks              52d
local-pv-53c7f822   3519Gi     RWO            Delete           Available                                 fast-disks              19h
...
```
(2) Launch a test job which will request a pod with one volume configured with `persistentVolumeClaim.claimName=pv-job-14c2ce8f-bd86-4a6f-a34a-jobmanager-jobmanager` and the PVC description like this:
```
Name:          pv-job-14c2ce8f-bd86-4a6f-a34a-jobmanager-jobmanager
Namespace:     blink
StorageClass:  fast-disks
Status:        Pending
Volume:
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type       Reason                Age   From                         Message
  ----       ------                ----  ----                         -------
  Normal     WaitForFirstConsumer  19s   persistentvolume-controller  waiting for first consumer to be created before binding
Mounted By:  job-14c2ce8f-bd86-4a6f-a34a-jobmanager-jobmanager-rc-hj4bx
```
This pod can start successfully based on default scheduler of K8s.

> I have a patch for this, @TaoYang526 could you please help to check if the changes in PR #68 works for you?

I have tested in my local test, it can works after fixing a minor issue(Task#schedulerCache is nil), I will test a lot later to confirm no other issues. Moreover, I want to know why we bind the volumes via calling `ctx.volumeBinder.Binder.BindPodVolumes(...)` in scheduler_cache.go? Is is better to do this in context.go as well as AssumePod?

**Comment by yangwwei** [comment]
Hi @TaoYang526 

Thanks for trying this out.
>  I want to know why we bind the volumes via calling ctx.volumeBinder.Binder.BindPodVolumes(...) in scheduler_cache.go? Is is better to do this in context.go as well as AssumePod?
Yeah, that was because we don't have `context` passed in `task`. Thinking over this, this patch needs some refinement, I think we can pass the volumeBinder into task instead of the schedulerCache, that will help to minimize the contact between layers. Does that make sense to you?

**Comment by TaoYang526** [comment]
> I think we can pass the volumeBinder into task instead of the schedulerCache, that will help to minimize the contact between layers. Does that make sense to you?
Make sense to me, thanks.

**Comment by wilfred-s** [comment]
While working through the review and looking at what we're doing I was wondering how you have setup the `StorageClass` in your cluster @TaoYang526 
I did notice during my testing that the auto create of a volume for a defined pvc could easily time out. All my testing used the `volumeBindingMode: Immediate` other modes used, especially with EBS volumes, gave weird behaviour on the kubernetes side.

**Comment by TaoYang526** [comment]
@wilfred-s 
We are using local PV which doesn't support dynamic provisioning currently, more details pls refer to https://kubernetes.io/docs/concepts/storage/storage-classes/#local
For this scenario, it's obvious that scheduler should support assuming/binding PV after choosing node, and we haven't tested other storage using dynamic provisioning yet.
